
server:
  port: 8083

spring:
  application:
    name: 'transportador'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3308/transportador
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka