
server:
  port: 8080

spring:
  application:
    name: 'loja'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3307/loja
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user